from fpdf import FPDF
from datetime import date
import os

def cover_letter(role, company, domain, greeting, cover_letter_path):

    height = 5
    font = "Arial"
    font_size = 10

    today = date.today()
    date_ll = today.strftime("%B %d, %Y")

    # save FPDF() class into a
    # variable pdf
    pdf = FPDF()
    
    # Add a page
    pdf.add_page()
    
    # set style and size of font
    # that you want in the pdf
    pdf.set_font(font, size = font_size)

    # Write header
    pdf.write(height, "Himalaya Sharma")
    pdf.write(height, "\n+1-548-333-4032")
    pdf.write(height, "\nhimalaya.sharma@uwaterloo.ca")
    pdf.write(height, f"\n{date_ll}")
    greeting = greeting + ','
    pdf.write(height, f"\n\n{greeting}")

    # Write paragraph 1
    pdf.write(height, f"\n\nI would like to introduce myself as an")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " applicant ")
    pdf.set_font(font, size = font_size)
    pdf.write(height, "for a potential ")
    # Insert role --------
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, role)
    # --------------------
    pdf.set_font(font, size = font_size)
    pdf.write(height, " position at ")
    # Insert company -----
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, company)
    # --------------------
    pdf.set_font(font, size = font_size)
    pdf.write(height, f". I am currently a")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " Master of Engineering ")
    pdf.set_font(font, size = font_size)
    pdf.write(height, "graduate student (with full-time status) in the ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Electrical and Computer Engineering ")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f"Department at ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "University of Waterloo")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " (in the penultimate term). I have strong interest in the field of ")
    # Insert domain ------
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, domain)
    # --------------------
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and I am confident in my ability to perform well due to my extensive education and research experience.")


    # Write paragraph 2
    pdf.write(height, f"\n\nDuring my")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " research internship ")
    pdf.set_font(font, size = font_size)
    pdf.write(height, "at ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Vienna University of Technology")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "New York University Abu Dhabi")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " under the supervision of ")
    pdf.set_text_color(0, 0, 255)
    pdf.write(height, "Prof. Dr.-Ing Muhammad Shafique", "https://scholar.google.com/citations?user=xSR276UAAAAJ&hl=en")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font, size = font_size)
    pdf.write(height, " my objective was to create an effective time series forecasting tool to predict future ECG data. I tested numerous ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "classical")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "deep learning forecasting models")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " to draw comparisons, experimented with different loss functions to enhance forecast performance, constructed model variants with different forecast horizons and optimized the workflow specifically for bio-signals. I had an extensive range of responsibilities including ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "data collection, data processing")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "data mining")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ". I was required to have excellent ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "communication skills")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ", understanding of ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "deep learning models")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ", excellence in usage of ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "TensorFlow")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "sklearn")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " toolkits, proficiency in ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "plotting tools")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ", knowledge of ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "SQL")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "applied statistics")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ". I have consolidated further on these skills by building multiple projects that bear real-world significance which can be viewed through my website ")
    pdf.set_text_color(0, 0, 255)
    pdf.write(height, "himalayasharma.github.io", "https://himalayasharma.github.io/")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font, size = font_size)
    pdf.write(height, f".")

    # Write paragraph 3
    pdf.write(height, f"\n\nRecently, I commenced")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " research work ")
    pdf.set_font(font, size = font_size)
    pdf.write(height, "at ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "University of Waterloo")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " as a")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " Graduate Research Assistant")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" under the supervision of ")
    pdf.set_text_color(0, 0, 255)
    pdf.write(height, "Prof. Zhou Wang", "https://scholar.google.ca/citations?user=O0PjM4QAAAAJ&hl=en")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" where I am working on ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "computer vision")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f". In addition to that I have joined the ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Ubiquitous Health Technology Lab")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" at ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "University of Waterloo")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" as a ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Data Science Intern")
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" under the supervision of ")
    pdf.set_text_color(0, 0, 255)
    pdf.write(height, "Prof. Plinio Morita", "https://scholar.google.ca/citations?user=pMiZZU4AAAAJ&hl=en")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font, size = font_size)
    pdf.write(height, f" where I am working on")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, " activity recognition")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " using physiological sensor data.")
    
    # Write paragraph 4
    pdf.write(height, f"\n\nMy abilities are rooted in a sturdy education in ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "engineering")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "biology")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ". I began with a ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "double major")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " in ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Bachelor of Engineering")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " (B.Eng.) in ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Electronics and Communication Engineering")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " and ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Master of Science")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " (M.Sc.) in ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Biological Sciences")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " from ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Birla Institute of Technology and Science, Pilani")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ", India. Following that as aforementioned, I am currently pursuing a ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Master of Engineering")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " (M.Eng.) at ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "University of Waterloo")
    pdf.set_font(font, size = font_size)
    pdf.write(height, " with an ")
    pdf.set_font(font, style='B', size = font_size)
    pdf.write(height, "Artificial Intelligence & Machine Learning specialization")
    pdf.set_font(font, size = font_size)
    pdf.write(height, ". I believe my personality has also played a major role in my ability to succeed in this career. I am extremely analytical, data-oriented, and calculated.\n\nI would like to thank you for taking the time to review my application. I look forward to hearing more and the details of the available position. I feel that my education and experience will ensure my success in this role.")

    # Write footer
    pdf.write(height, f"\n\nSincerely,\nHimalaya Sharma")

    # save the pdf with name .pdf
    pdf.output(cover_letter_path)

    return None